### ISSUE TITLE
bug, close cause panic

### ISSUE THREAD

**Issue by xiaoyang-chen** [rabbitmq/amqp091-go#130]
```bash
[root@edge-chengli-00001 rabbitmq-queue-declarer]# docker logs -f 81d03ce572f3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x54 pc=0x7aaddc]

goroutine 465 [running]:
github.com/rabbitmq/amqp091-go.(*Channel).setClosed(...)
	/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.4.0/channel.go:94
github.com/rabbitmq/amqp091-go.updateChannel(...)
	/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.4.0/types.go:321
github.com/rabbitmq/amqp091-go.(*Connection).dispatchN(0xc000344140, {0xd7a958, 0xc00019e4e0?})
	/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.4.0/connection.go:516 +0xbc
github.com/rabbitmq/amqp091-go.(*Connection).demux(0xc000085f28?, {0xd7a958, 0xc00019e4e0})
	/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.4.0/connection.go:477 +0x5b
github.com/rabbitmq/amqp091-go.(*Connection).reader(0xc000344140, {0xd78300?, 0xc0005aa090?})
	/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.4.0/connection.go:577 +0x227
created by github.com/rabbitmq/amqp091-go.Open
	/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.4.0/connection.go:258 +0x34a
```

**Comment by Zerpet** [comment]
Without code to reproduce this issue, and a brief description of the situation, there's little we can do to investigate this panic.
