### ISSUE TITLE
Package panics at connection.Channel

### ISSUE THREAD

**Issue by belchushka** [rabbitmq/amqp091-go#220]
### Describe the bug

Package panics after trying to open connection channel

```go

connectionString := fmt.Sprintf("amqp://%s:%s@%s:%s/", cfg.User, cfg.Password, cfg.Host, cfg.Port)

err := utils.DoWithAttempts(func(attempt int) error {
log.Println("Attempt to connect: " + fmt.Sprintf("%d", attempt+1), connectionString)

conn, err := amqp.Dial(connectionString)

if err != nil {
	log.Println("Failed to connect to rabbitMq... going to do next attempt", err)
	return err
}

ch, err := connection.Channel() // <- here 

if err != nil {
	log.Println("Failed to connect to rabbitMq... going to do next attempt", err)
	return err
}

connection = conn

connectionChan = ch
return nil
}, DELAY, MAX_ATTEMPTS)

if err != nil {
log.Println("Failed to connect to rabbitMq", err)
return nil, err
}
```

Panic message:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101119b3c]

goroutine 1 [running]:
github.com/rabbitmq/amqp091-go.(*Connection).allocateChannel(0x1400037d3e7?)
        /Users/belchushka/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/connection.go:796 +0x2c
github.com/rabbitmq/amqp091-go.(*Connection).openChannel(0x1400037d3e0?)
        /Users/belchushka/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/connection.go:828 +0x20
github.com/rabbitmq/amqp091-go.(*Connection).Channel(...)
        /Users/belchushka/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/connection.go:854
lab18.matbea.xyz/gpt/bothub-support/pkg/messageBroker.NewMessageBrokerClient.func1(0x12a05f200?)
        /Users/belchushka/Documents/hashbon/bothub-support/pkg/messageBroker/messageBroker.go:53 +0x200
lab18.matbea.xyz/gpt/bothub-support/pkg/lib.DoWithAttempts(0x1400193db60, 0x13?, 0x5)
        /Users/belchushka/Documents/hashbon/bothub-support/pkg/lib/lib.go:11 +0x68
lab18.matbea.xyz/gpt/bothub-support/pkg/messageBroker.NewMessageBrokerClient(0x1400193dcf0)
        /Users/belchushka/Documents/hashbon/bothub-support/pkg/messageBroker/messageBroker.go:43 +0x11c
lab18.matbea.xyz/gpt/bothub-support/internal/app.NewApp({0x101510b38?, 0x1400052d4a0})
        /Users/belchushka/Documents/hashbon/bothub-support/internal/app/app.go:57 +0x2a0
main.main()
        /Users/belchushka/Documents/hashbon/bothub-support/cmd/main.go:21 +0x70
exit status 2
```

Opening channel on the other side (python microservice) works fine

### Reproduction steps

1. Open amqp connection
2. Try to open connection channel

### Expected behavior

Successfully opened connection channel

### Additional context

OS: MacOS Ventura
Chip: Apple m2 (arm)
Go 1.20.7
RabbitMQ 3.12
RabbitMQ Env: Docker

**Comment by lukebakken** [comment]
@belchushka would you mind sharing what the real issue turned out to be?

As you have found out, rarely will you find a bug in the software you're using, especially for such a basic operation. It's almost always your own code 😸
