### ISSUE TITLE
connection block when write connection reset by peer

### ISSUE THREAD

**Issue by yywing** [rabbitmq/amqp091-go#222]
### Describe the bug

version: v1.8.1

NotifyClose got error：
```
time="2023-09-26T10:09:02Z" level=warning msg="Monitor NotifyClose: Exception (501) Reason: \"write tcp 169.254.1.1:47048->169.254.1.5:5672: write: connection reset by peer\"" func=mq
```

pprof block:
```
goroutine 52 [select, 101 minutes]:
github.com/rabbitmq/amqp091-go.(*Channel).call(0xc00041eea0, {0xcbf328, 0xc00040d420}, {0xc0003553f8, 0x1, 0x0?})
	/etst/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/channel.go:178 +0xff
github.com/rabbitmq/amqp091-go.(*Channel).open(...)
	/etst/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/channel.go:167
github.com/rabbitmq/amqp091-go.(*Connection).openChannel(0xc000302be8?)
	/etst/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/connection.go:833 +0x98
github.com/rabbitmq/amqp091-go.(*Connection).Channel(...)
	/etst/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/connection.go:854
....

goroutine 214 [chan receive, 101 minutes]:
github.com/rabbitmq/amqp091-go.(*Connection).call(0xc0002bcdc0, {0xcbf440?, 0xc000336a00?}, {0xc000116d60, 0x1, 0xc000116d88?})
	/etst/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/connection.go:866 +0xee
github.com/rabbitmq/amqp091-go.(*Connection).closeWith(0xc0002bcdc0, 0x1129120)
	/etst/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/connection.go:443 +0x10a
github.com/rabbitmq/amqp091-go.(*Connection).dispatchClosed(0xc000414947?, {0xcbc258?, 0xc00031ef48?})
	/etst/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/connection.go:692 +0x1f9
github.com/rabbitmq/amqp091-go.(*Connection).dispatchN(0xc0002bcdc0, {0xcbc258?, 0xc00031ef48?})
	/etst/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/connection.go:664 +0x1e5
github.com/rabbitmq/amqp091-go.(*Connection).demux(0xc000116f28?, {0xcbc258, 0xc00031ef48})
	/etst/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/connection.go:613 +0x5b
github.com/rabbitmq/amqp091-go.(*Connection).reader(0xc0002bcdc0, {0xcba440?, 0xc00029c168?})
	/etst/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/connection.go:717 +0x23d
created by github.com/rabbitmq/amqp091-go.Open
	/etst/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/rabbitmq/amqp091-go@v1.8.1/connection.go:268 +0x34c
```

### Reproduction steps

close mq connection by hand

### Expected behavior

no block

### Additional context

There are two goroutine are wired. Maybe there is two bug?

Code like:
```golang
var conn *amqp.Connection
var mqAddr string

go func() {
   for {
      ch := conn.Channel()
      <-channel.NotifyClose(make(chan *amqp.Error, 1))
      channel.Close()
   }
}

go func() {
   for {
      conn := amqp.Dial(mqAddr)
      <-conn.NotifyClose(make(chan *amqp.Error, 1))
      conn.Close()
   }
}


```

**Comment by lukebakken** [comment]
Please help us help you by providing enough information that we can easily reproduce this issue:

* Share the source code to a runnable program that exhibits this issue. Provide the code via a git repository that I can clone, compile, and run.
* What does "close mq connection by hand" mean, **exactly**? Did you close the connection using `rabbitmqctl` the RabbitMQ management web UI, or some other means?
* How did you get the `pprof block` output?

**Comment by yywing** [comment]
> close mq connection by hand
`rabbitmqctl close_connection <connection pid>`

**Comment by yywing** [comment]
`dlv` attach, read args, found:

goroutine 52 and goroutine 214 use some connection.

connection.close  is `1`
channel.close is `0`

```
*github.com/rabbitmq/amqp091-go.Channel {
	destructor: sync.Once {
		done: 0,
		m: (*sync.Mutex)(0xc00041eea4),},
	m: sync.Mutex {state: 0, sema: 0},
	confirmM: sync.Mutex {state: 0, sema: 0},
	notifyM: sync.RWMutex {
		w: (*sync.Mutex)(0xc00041eebc),
		writerSem: 0,
		readerSem: 0,
		readerCount: 0,
		readerWait: 0,},
	connection: *github.com/rabbitmq/amqp091-go.Connection {
		destructor: (*sync.Once)(0xc0002bcdc0),
		sendM: (*sync.Mutex)(0xc0002bcdcc),
		m: (*sync.Mutex)(0xc0002bcdd4),
		conn: io.ReadWriteCloser(*net.TCPConn) ...,
		rpc: chan github.com/rabbitmq/amqp091-go.message {
			qcount: 0,
			dataqsiz: 0,
			buf: *[0]github.com/rabbitmq/amqp091-go.message [],
			elemsize: 16,
			closed: 0,
			elemtype: *runtime._type {size: 16, ptrdata: 16, hash: 1373990021, tflag: tflagUncommon|tflagExtraStar|tflagNamed (7), align: 8, fieldAlign: 8, kind: 20, equal: runtime.interequal, gcdata: *2, str: 87135, ptrToThis: 281920},
			sendx: 0,
			recvx: 0,
			recvq: waitq<github.com/rabbitmq/amqp091-go.message> {
				first: *(*"sudog<github.com/rabbitmq/amqp091-go.message>")(0xc00014b920),
				last: *(*"sudog<github.com/rabbitmq/amqp091-go.message>")(0xc00014b920),},
			sendq: waitq<github.com/rabbitmq/amqp091-go.message> {
				first: *sudog<github.com/rabbitmq/amqp091-go.message> nil,
				last: *sudog<github.com/rabbitmq/amqp091-go.message> nil,},
			lock: runtime.mutex {
				lockRankStruct: runtime.lockRankStruct {},
				key: 0,},},
		writer: *(*"github.com/rabbitmq/amqp091-go.writer")(0xc0003aa040),
		sends: chan time.Time {
			qcount: 0,
			dataqsiz: 0,
			buf: *[0]time.Time [],
			elemsize: 24,
			closed: 0,
			elemtype: *runtime._type {size: 24, ptrdata: 24, hash: 2360098281, tflag: tflagUncommon|tflagExtraStar|tflagNamed|tflagRegularMemory (15), align: 8, fieldAlign: 8, kind: 25, equal: runtime.memequal_varlen, gcdata: *4, str: 35838, ptrToThis: 1567104},
			sendx: 0,
			recvx: 0,
			recvq: waitq<time.Time> {
				first: *sudog<time.Time> nil,
				last: *sudog<time.Time> nil,},
			sendq: waitq<time.Time> {
				first: *sudog<time.Time> nil,
				last: *sudog<time.Time> nil,},
			lock: runtime.mutex {
				lockRankStruct: runtime.lockRankStruct {},
				key: 0,},},
		deadlines: chan github.com/rabbitmq/amqp091-go.readDeadliner {
			qcount: 0,
			dataqsiz: 1,
			buf: *[1]github.com/rabbitmq/amqp091-go.readDeadliner [
				nil,
			],
			elemsize: 16,
			closed: 0,
			elemtype: *runtime._type {size: 16, ptrdata: 16, hash: 2953390639, tflag: tflagUncommon|tflagExtraStar|tflagNamed (7), align: 8, fieldAlign: 8, kind: 20, equal: runtime.interequal, gcdata: *2, str: 136651, ptrToThis: 282112},
			sendx: 0,
			recvx: 0,
			recvq: waitq<github.com/rabbitmq/amqp091-go.readDeadliner> {
				first: *sudog<github.com/rabbitmq/amqp091-go.readDeadliner> nil,
				last: *sudog<github.com/rabbitmq/amqp091-go.readDeadliner> nil,},
			sendq: waitq<github.com/rabbitmq/amqp091-go.readDeadliner> {
				first: *sudog<github.com/rabbitmq/amqp091-go.readDeadliner> nil,
				last: *sudog<github.com/rabbitmq/amqp091-go.readDeadliner> nil,},
			lock: runtime.mutex {
				lockRankStruct: runtime.lockRankStruct {},
				key: 0,},},
		allocator: *github.com/rabbitmq/amqp091-go.allocator nil,
		channels: map[uint16]*github.com/rabbitmq/amqp091-go.Channel nil,
		noNotify: true,
		closes: []chan *github.com/rabbitmq/amqp091-go.Error len: 2, cap: 2, [chan *github.com/rabbitmq/amqp091-go.Error 1/1,chan *github.com/rabbitmq/amqp091-go.Error 0/1],
		blocks: []chan github.com/rabbitmq/amqp091-go.Blocking len: 0, cap: 0, nil,
		errors: chan *github.com/rabbitmq/amqp091-go.Error {
			qcount: 1,
			dataqsiz: 1,
			buf: *[1]*github.com/rabbitmq/amqp091-go.Error [
				*(*"github.com/rabbitmq/amqp091-go.Error")(0xc000336a40),
			],
			elemsize: 8,
			closed: 1,
			elemtype: *runtime._type {size: 8, ptrdata: 8, hash: 1127058806, tflag: tflagUncommon|tflagRegularMemory (9), align: 8, fieldAlign: 8, kind: 54, equal: runtime.memequal64, gcdata: *1, str: 70464, ptrToThis: 0},
			sendx: 0,
			recvx: 0,
			recvq: waitq<*github.com/rabbitmq/amqp091-go.Error> {
				first: *sudog<*github.com/rabbitmq/amqp091-go.Error> nil,
				last: *sudog<*github.com/rabbitmq/amqp091-go.Error> nil,},
			sendq: waitq<*github.com/rabbitmq/amqp091-go.Error> {
				first: *sudog<*github.com/rabbitmq/amqp091-go.Error> nil,
				last: *sudog<*github.com/rabbitmq/amqp091-go.Error> nil,},
			lock: runtime.mutex {
				lockRankStruct: runtime.lockRankStruct {},
				key: 0,},},
		Config: (*"github.com/rabbitmq/amqp091-go.Config")(0xc0002bce60),
		Major: 0,
		Minor: 9,
		Properties: github.com/rabbitmq/amqp091-go.Table [...],
		Locales: []string len: 1, cap: 1, ["en_US"],
		closed: 1,},
	rpc: chan github.com/rabbitmq/amqp091-go.message {
		qcount: 0,
		dataqsiz: 0,
		buf: *[0]github.com/rabbitmq/amqp091-go.message [],
		elemsize: 16,
		closed: 0,
		elemtype: *runtime._type {size: 16, ptrdata: 16, hash: 1373990021, tflag: tflagUncommon|tflagExtraStar|tflagNamed (7), align: 8, fieldAlign: 8, kind: 20, equal: runtime.interequal, gcdata: *2, str: 87135, ptrToThis: 281920},
		sendx: 0,
		recvx: 0,
		recvq: waitq<github.com/rabbitmq/amqp091-go.message> {
			first: *(*"sudog<github.com/rabbitmq/amqp091-go.message>")(0xc0002ee300),
			last: *(*"sudog<github.com/rabbitmq/amqp091-go.message>")(0xc0002ee300),},
		sendq: waitq<github.com/rabbitmq/amqp091-go.message> {
			first: *sudog<github.com/rabbitmq/amqp091-go.message> nil,
			last: *sudog<github.com/rabbitmq/amqp091-go.message> nil,},
		lock: runtime.mutex {
			lockRankStruct: runtime.lockRankStruct {},
			key: 0,},},
	consumers: *github.com/rabbitmq/amqp091-go.consumers {
		WaitGroup: (*sync.WaitGroup)(0xc000422270),
		closed: chan struct {} {
			qcount: 0,
			dataqsiz: 0,
			buf: *[0]struct struct {} [],
			elemsize: 0,
			closed: 0,
			elemtype: *runtime._type {size: 0, ptrdata: 0, hash: 3842252374, tflag: tflagExtraStar|tflagRegularMemory (10), align: 1, fieldAlign: 1, kind: 25, equal: runtime.memequal0, gcdata: *0, str: 35778, ptrToThis: 0},
			sendx: 0,
			recvx: 0,
			recvq: waitq<struct {}> {
				first: *sudog<struct {}> nil,
				last: *sudog<struct {}> nil,},
			sendq: waitq<struct {}> {
				first: *sudog<struct {}> nil,
				last: *sudog<struct {}> nil,},
			lock: runtime.mutex {
				lockRankStruct: runtime.lockRankStruct {},
				key: 0,},},
		Mutex: (*sync.Mutex)(0xc000422288),
		chans: github.com/rabbitmq/amqp091-go.consumerBuffers [],},
	id: 1,
	closed: 0,
	noNotify: false,
	closes: []chan *github.com/rabbitmq/amqp091-go.Error len: 0, cap: 0, nil,
	flows: []chan bool len: 0, cap: 0, nil,
	returns: []chan github.com/rabbitmq/amqp091-go.Return len: 0, cap: 0, nil,
	cancels: []chan string len: 0, cap: 0, nil,
	confirms: *github.com/rabbitmq/amqp091-go.confirms {
		m: (*sync.Mutex)(0xc000416820),
		listeners: []chan github.com/rabbitmq/amqp091-go.Confirmation len: 0, cap: 0, nil,
		sequencer: map[uint64]github.com/rabbitmq/amqp091-go.Confirmation [],
		deferredConfirmations: *(*"github.com/rabbitmq/amqp091-go.deferredConfirmations")(0xc00040d410),
		published: 0,
		publishedMut: (*sync.Mutex)(0xc000416858),
		expecting: 1,},
	confirming: false,
	errors: chan *github.com/rabbitmq/amqp091-go.Error {
		qcount: 0,
		dataqsiz: 1,
		buf: *[1]*github.com/rabbitmq/amqp091-go.Error [
			*nil,
		],
		elemsize: 8,
		closed: 0,
		elemtype: *runtime._type {size: 8, ptrdata: 8, hash: 1127058806, tflag: tflagUncommon|tflagRegularMemory (9), align: 8, fieldAlign: 8, kind: 54, equal: runtime.memequal64, gcdata: *1, str: 70464, ptrToThis: 0},
		sendx: 0,
		recvx: 0,
		recvq: waitq<*github.com/rabbitmq/amqp091-go.Error> {
			first: *(*"sudog<*github.com/rabbitmq/amqp091-go.Error>")(0xc000338180),
			last: *(*"sudog<*github.com/rabbitmq/amqp091-go.Error>")(0xc000338180),},
		sendq: waitq<*github.com/rabbitmq/amqp091-go.Error> {
			first: *sudog<*github.com/rabbitmq/amqp091-go.Error> nil,
			last: *sudog<*github.com/rabbitmq/amqp091-go.Error> nil,},
		lock: runtime.mutex {
			lockRankStruct: runtime.lockRankStruct {},
			key: 0,},},
	recv: github.com/rabbitmq/amqp091-go.(*Channel).recvMethod,
	message: github.com/rabbitmq/amqp091-go.messageWithContent nil,
	header: *github.com/rabbitmq/amqp091-go.headerFrame nil,
	body: []uint8 len: 0, cap: 0, nil,}
(dlv) print ch.connection
print ch.connection
*github.com/rabbitmq/amqp091-go.Connection {
	destructor: sync.Once {
		done: 1,
		m: (*sync.Mutex)(0xc0002bcdc4),},
	sendM: sync.Mutex {state: 0, sema: 0},
	m: sync.Mutex {state: 0, sema: 0},
	conn: io.ReadWriteCloser(*net.TCPConn) *{
		conn: (*net.conn)(0xc00029c168),},
	rpc: chan github.com/rabbitmq/amqp091-go.message {
		qcount: 0,
		dataqsiz: 0,
		buf: *[0]github.com/rabbitmq/amqp091-go.message [],
		elemsize: 16,
		closed: 0,
		elemtype: *runtime._type {size: 16, ptrdata: 16, hash: 1373990021, tflag: tflagUncommon|tflagExtraStar|tflagNamed (7), align: 8, fieldAlign: 8, kind: 20, equal: runtime.interequal, gcdata: *2, str: 87135, ptrToThis: 281920},
		sendx: 0,
		recvx: 0,
		recvq: waitq<github.com/rabbitmq/amqp091-go.message> {
			first: *(*"sudog<github.com/rabbitmq/amqp091-go.message>")(0xc00014b920),
			last: *(*"sudog<github.com/rabbitmq/amqp091-go.message>")(0xc00014b920),},
		sendq: waitq<github.com/rabbitmq/amqp091-go.message> {
			first: *sudog<github.com/rabbitmq/amqp091-go.message> nil,
			last: *sudog<github.com/rabbitmq/amqp091-go.message> nil,},
		lock: runtime.mutex {
			lockRankStruct: runtime.lockRankStruct {},
			key: 0,},},
	writer: *github.com/rabbitmq/amqp091-go.writer {
		w: io.Writer(*bufio.Writer) ...,},
	sends: chan time.Time {
		qcount: 0,
		dataqsiz: 0,
		buf: *[0]time.Time [],
		elemsize: 24,
		closed: 0,
		elemtype: *runtime._type {size: 24, ptrdata: 24, hash: 2360098281, tflag: tflagUncommon|tflagExtraStar|tflagNamed|tflagRegularMemory (15), align: 8, fieldAlign: 8, kind: 25, equal: runtime.memequal_varlen, gcdata: *4, str: 35838, ptrToThis: 1567104},
		sendx: 0,
		recvx: 0,
		recvq: waitq<time.Time> {
			first: *sudog<time.Time> nil,
			last: *sudog<time.Time> nil,},
		sendq: waitq<time.Time> {
			first: *sudog<time.Time> nil,
			last: *sudog<time.Time> nil,},
		lock: runtime.mutex {
			lockRankStruct: runtime.lockRankStruct {},
			key: 0,},},
	deadlines: chan github.com/rabbitmq/amqp091-go.readDeadliner {
		qcount: 0,
		dataqsiz: 1,
		buf: *[1]github.com/rabbitmq/amqp091-go.readDeadliner [
			nil,
		],
		elemsize: 16,
		closed: 0,
		elemtype: *runtime._type {size: 16, ptrdata: 16, hash: 2953390639, tflag: tflagUncommon|tflagExtraStar|tflagNamed (7), align: 8, fieldAlign: 8, kind: 20, equal: runtime.interequal, gcdata: *2, str: 136651, ptrToThis: 282112},
		sendx: 0,
		recvx: 0,
		recvq: waitq<github.com/rabbitmq/amqp091-go.readDeadliner> {
			first: *sudog<github.com/rabbitmq/amqp091-go.readDeadliner> nil,
			last: *sudog<github.com/rabbitmq/amqp091-go.readDeadliner> nil,},
		sendq: waitq<github.com/rabbitmq/amqp091-go.readDeadliner> {
			first: *sudog<github.com/rabbitmq/amqp091-go.readDeadliner> nil,
			last: *sudog<github.com/rabbitmq/amqp091-go.readDeadliner> nil,},
		lock: runtime.mutex {
			lockRankStruct: runtime.lockRankStruct {},
			key: 0,},},
	allocator: *github.com/rabbitmq/amqp091-go.allocator nil,
	channels: map[uint16]*github.com/rabbitmq/amqp091-go.Channel nil,
	noNotify: true,
	closes: []chan *github.com/rabbitmq/amqp091-go.Error len: 2, cap: 2, [chan *github.com/rabbitmq/amqp091-go.Error 1/1,chan *github.com/rabbitmq/amqp091-go.Error 0/1],
	blocks: []chan github.com/rabbitmq/amqp091-go.Blocking len: 0, cap: 0, nil,
	errors: chan *github.com/rabbitmq/amqp091-go.Error {
		qcount: 1,
		dataqsiz: 1,
		buf: *[1]*github.com/rabbitmq/amqp091-go.Error [
			*(*"github.com/rabbitmq/amqp091-go.Error")(0xc000336a40),
		],
		elemsize: 8,
		closed: 1,
		elemtype: *runtime._type {size: 8, ptrdata: 8, hash: 1127058806, tflag: tflagUncommon|tflagRegularMemory (9), align: 8, fieldAlign: 8, kind: 54, equal: runtime.memequal64, gcdata: *1, str: 70464, ptrToThis: 0},
		sendx: 0,
		recvx: 0,
		recvq: waitq<*github.com/rabbitmq/amqp091-go.Error> {
			first: *sudog<*github.com/rabbitmq/amqp091-go.Error> nil,
			last: *sudog<*github.com/rabbitmq/amqp091-go.Error> nil,},
		sendq: waitq<*github.com/rabbitmq/amqp091-go.Error> {
			first: *sudog<*github.com/rabbitmq/amqp091-go.Error> nil,
			last: *sudog<*github.com/rabbitmq/amqp091-go.Error> nil,},
		lock: runtime.mutex {
			lockRankStruct: runtime.lockRankStruct {},
			key: 0,},},
	Config: github.com/rabbitmq/amqp091-go.Config {
		SASL: []github.com/rabbitmq/amqp091-go.Authentication len: 1, cap: 1, [
			...,
		],
		Vhost: "scanner",
		ChannelMax: 51711,
		FrameSize: 131072,
		Heartbeat: github.com/rabbitmq/amqp091-go.defaultHeartbeat (10000000000),
		TLSClientConfig: *crypto/tls.Config nil,
		Properties: github.com/rabbitmq/amqp091-go.Table nil,
		Locale: "en_US",
		Dial: nil,},
	Major: 0,
	Minor: 9,
	Properties: github.com/rabbitmq/amqp091-go.Table [
		"capabilities": *(*interface {})(0xc00037c868),
		"cluster_name": *(*interface {})(0xc00037c878),
		"copyright": *(*interface {})(0xc00037c888),
		"information": *(*interface {})(0xc00037c898),
		"platform": *(*interface {})(0xc00037c8a8),
		"product": *(*interface {})(0xc00037c8b8),
		"version": *(*interface {})(0xc00037c8c8),
	],
	Locales: []string len: 1, cap: 1, ["en_US"],
	closed: 1,}
```

**Comment by yywing** [comment]
goroutine 52 block reason:

1. `old := connection.Channel()` open channel id 1
2. `old.Close()` delete `contection.channels` id 1,and release id 1
3. `new := connection.Channel()` open new channel id 1 and add id 1 to `contection.channels`
4. `old.Close()` will delete `contection.channels` id 1 which id point to new.
5. new channel will leak, `connection.shutdown()` nerver close new channel

https://github.com/rabbitmq/amqp091-go/blob/831d90b23adc138f79c0c661a21b8455fefbf149/channel.go#L468

not safe enough - -

**Comment by yywing** [comment]
goroutine 214 block reason：

https://github.com/rabbitmq/amqp091-go/blob/831d90b23adc138f79c0c661a21b8455fefbf149/connection.go#L857-L866

`req == nil` or `c.send` no err, will block at `<- c.rpc`.
And then net.Conn break like ` write: connection reset by peer`.
`connection.shutdown()` call in other goroutine.
And this goroutine will block for ever.

**Comment by yywing** [comment]
```golang
package main

import (
	"fmt"
	"reflect"
	"time"

	"net/http"
	_ "net/http/pprof"

	amqp "github.com/rabbitmq/amqp091-go"
)

var mqAddr string = "amqp://scanner:scanner@localhost:5672/scanner"

func getID(ch *amqp.Channel) uint64 {
	return reflect.ValueOf(ch).Elem().FieldByName("id").Uint()
}

func getC(c *amqp.Connection) {
	fmt.Println("list:")
	keys := reflect.ValueOf(c).Elem().FieldByName("channels").MapKeys()
	for _, i := range keys {
		fmt.Println(i.Uint())
	}
}

func main() {
	go func() {
		fmt.Println(http.ListenAndServe("localhost:6060", nil))
	}()

	c, err := amqp.Dial(mqAddr)
	if err != nil {
		panic(err)
	}

	ch, err := c.Channel()
	if err != nil {
		panic(err)
	}
	err = ch.Close()
	if err != nil {
		panic(err)
	}
	oldID := getID(ch)

	var newID uint64
	var new *amqp.Channel
	for {
		ch, err := c.Channel()
		if err != nil {
			panic(err)
		}
		newID = getID(ch)
		if oldID == newID {
			new = ch
			break
		}
	}

	getC(c)
	fmt.Println("found !!!!", oldID, newID)
	// new channel leak
	ch.Close()
	getC(c)

	// new channel do any call will block
	_, err = new.QueueDeclare("111", true, false, false, false, nil)
	if err != nil {
		panic(err)
	}
	fmt.Println("never reach!")
	time.Sleep(10 * time.Hour)
}
```
pprof:
```
goroutine 37 [running]:
runtime/pprof.writeGoroutineStacks({0x1398f20, 0xc0001e0000})
	/test/.gvm/gos/go1.19/src/runtime/pprof/pprof.go:692 +0x70
runtime/pprof.writeGoroutine({0x1398f20?, 0xc0001e0000?}, 0xc0001b20d0?)
	/test/.gvm/gos/go1.19/src/runtime/pprof/pprof.go:681 +0x2b
runtime/pprof.(*Profile).WriteTo(0x12f19c0?, {0x1398f20?, 0xc0001e0000?}, 0xc?)
	/test/.gvm/gos/go1.19/src/runtime/pprof/pprof.go:330 +0x14b
net/http/pprof.handler.ServeHTTP({0xc0001d0011, 0x9}, {0x139b040, 0xc0001e0000}, 0x736f686c61636f6c?)
	/test/.gvm/gos/go1.19/src/net/http/pprof/pprof.go:253 +0x4a5
net/http/pprof.Index({0x139b040?, 0xc0001e0000}, 0xc0001cc000)
	/test/.gvm/gos/go1.19/src/net/http/pprof/pprof.go:371 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc0000bfaf0?, {0x139b040?, 0xc0001e0000?}, 0x0?)
	/test/.gvm/gos/go1.19/src/net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0001d001b?, {0x139b040, 0xc0001e0000}, 0xc0001cc000)
	/test/.gvm/gos/go1.19/src/net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0xc000194480?}, {0x139b040, 0xc0001e0000}, 0xc0001cc000)
	/test/.gvm/gos/go1.19/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0001be000, {0x139b500, 0xc0000a3560})
	/test/.gvm/gos/go1.19/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/test/.gvm/gos/go1.19/src/net/http/server.go:3102 +0x4db

goroutine 1 [select]:
github.com/rabbitmq/amqp091-go.(*Channel).call(0xc0000d8480, {0x139c108, 0xc000194330}, {0xc0000d1e70, 0x1, 0x130b7a0?})
	/test/github/amqp091-go/channel.go:178 +0xff
github.com/rabbitmq/amqp091-go.(*Channel).QueueDeclare(0xc0000f52c0?, {0x1313bf3, 0x3}, 0x1, 0x0, 0x0, 0x0, 0x0)
	/test/github/amqp091-go/channel.go:813 +0x157
main.main()
	/test/github/amqp091-go/test/main.go:69 +0x20e

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x35800d8, 0x72)
	/test/.gvm/gos/go1.19/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc00010a680?, 0x4?, 0x0)
	/test/.gvm/gos/go1.19/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/test/.gvm/gos/go1.19/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00010a680)
	/test/.gvm/gos/go1.19/src/internal/poll/fd_unix.go:614 +0x234
net.(*netFD).accept(0xc00010a680)
	/test/.gvm/gos/go1.19/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc0000aa1c8)
	/test/.gvm/gos/go1.19/src/net/tcpsock_posix.go:142 +0x28
net.(*TCPListener).Accept(0xc0000aa1c8)
	/test/.gvm/gos/go1.19/src/net/tcpsock.go:288 +0x3d
net/http.(*Server).Serve(0xc000180000, {0x139ae90, 0xc0000aa1c8})
	/test/.gvm/gos/go1.19/src/net/http/server.go:3070 +0x385
net/http.(*Server).ListenAndServe(0xc000180000)
	/test/.gvm/gos/go1.19/src/net/http/server.go:2999 +0x7d
net/http.ListenAndServe(...)
	/test/.gvm/gos/go1.19/src/net/http/server.go:3255
main.main.func1()
	/test/github/amqp091-go/test/main.go:30 +0x45
created by main.main
	/test/github/amqp091-go/test/main.go:29 +0x32

goroutine 24 [chan receive]:
github.com/rabbitmq/amqp091-go.(*Connection).call(0xc0000f52c0, {0x139bc00?, 0xc0000d2580?}, {0xc000188d60, 0x1, 0xc000188d88?})
	/test/github/amqp091-go/connection.go:866 +0xee
github.com/rabbitmq/amqp091-go.(*Connection).closeWith(0xc0000f52c0, 0x1548cc0)
	/test/github/amqp091-go/connection.go:443 +0x10a
github.com/rabbitmq/amqp091-go.(*Connection).dispatchClosed(0xc0001903f4?, {0x139a230?, 0xc0000aa288?})
	/test/github/amqp091-go/connection.go:692 +0x1f9
github.com/rabbitmq/amqp091-go.(*Connection).dispatchN(0xc0000f52c0, {0x139a230?, 0xc0000aa288?})
	/test/github/amqp091-go/connection.go:664 +0x1e5
github.com/rabbitmq/amqp091-go.(*Connection).demux(0xc000188f28?, {0x139a230, 0xc0000aa288})
	/test/github/amqp091-go/connection.go:613 +0x5b
github.com/rabbitmq/amqp091-go.(*Connection).reader(0xc0000f52c0, {0x35841b8?, 0xc0000b00a8?})
	/test/github/amqp091-go/connection.go:717 +0x23d
created by github.com/rabbitmq/amqp091-go.Open
	/test/github/amqp091-go/connection.go:268 +0x34c

goroutine 36 [select]:
github.com/rabbitmq/amqp091-go.(*Connection).heartbeater(0xc0000f52c0, 0x12a05f200, 0xc0001921e0)
	/test/github/amqp091-go/connection.go:745 +0x1bf
created by github.com/rabbitmq/amqp091-go.(*Connection).openTune
	/test/github/amqp091-go/connection.go:996 +0x739

goroutine 38 [IO wait]:
internal/poll.runtime_pollWait(0x357fe08, 0x72)
	/test/.gvm/gos/go1.19/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc0001a4100?, 0xc0001ce000?, 0x0)
	/test/.gvm/gos/go1.19/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/test/.gvm/gos/go1.19/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0001a4100, {0xc0001ce000, 0x1000, 0x1000})
	/test/.gvm/gos/go1.19/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0001a4100, {0xc0001ce000?, 0xc0001826c0?, 0x1226925?})
	/test/.gvm/gos/go1.19/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0001a0020, {0xc0001ce000?, 0x0?, 0x0?})
	/test/.gvm/gos/go1.19/src/net/net.go:183 +0x45
net/http.(*connReader).Read(0xc000194570, {0xc0001ce000, 0x1000, 0x1000})
	/test/.gvm/gos/go1.19/src/net/http/server.go:786 +0x171
bufio.(*Reader).fill(0xc0001922a0)
	/test/.gvm/gos/go1.19/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).ReadSlice(0xc0001922a0, 0x0?)
	/test/.gvm/gos/go1.19/src/bufio/bufio.go:372 +0x2f
bufio.(*Reader).ReadLine(0xc0001922a0)
	/test/.gvm/gos/go1.19/src/bufio/bufio.go:401 +0x27
net/textproto.(*Reader).readLineSlice(0xc0001945a0)
	/test/.gvm/gos/go1.19/src/net/textproto/reader.go:56 +0x99
net/textproto.(*Reader).ReadLine(...)
	/test/.gvm/gos/go1.19/src/net/textproto/reader.go:37
net/http.readRequest(0xc0001a0020?)
	/test/.gvm/gos/go1.19/src/net/http/request.go:1036 +0x79
net/http.(*conn).readRequest(0xc0001be0a0, {0x139b458, 0xc00018e200})
	/test/.gvm/gos/go1.19/src/net/http/server.go:994 +0x24a
net/http.(*conn).serve(0xc0001be0a0, {0x139b500, 0xc0000a3560})
	/test/.gvm/gos/go1.19/src/net/http/server.go:1916 +0x345
created by net/http.(*Server).Serve
	/test/.gvm/gos/go1.19/src/net/http/server.go:3102 +0x4db

goroutine 39 [IO wait]:
internal/poll.runtime_pollWait(0x357fef8, 0x72)
	/test/.gvm/gos/go1.19/src/runtime/netpoll.go:305 +0x89
internal/poll.(*pollDesc).wait(0xc0001a4080?, 0xc000194491?, 0x0)
	/test/.gvm/gos/go1.19/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/test/.gvm/gos/go1.19/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0001a4080, {0xc000194491, 0x1, 0x1})
	/test/.gvm/gos/go1.19/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0001a4080, {0xc000194491?, 0x0?, 0x0?})
	/test/.gvm/gos/go1.19/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0001a0018, {0xc000194491?, 0x0?, 0x0?})
	/test/.gvm/gos/go1.19/src/net/net.go:183 +0x45
net/http.(*connReader).backgroundRead(0xc000194480)
	/test/.gvm/gos/go1.19/src/net/http/server.go:678 +0x3f
created by net/http.(*connReader).startBackgroundRead
	/test/.gvm/gos/go1.19/src/net/http/server.go:674 +0xca
```

**Comment by yywing** [comment]
my pr is ready https://github.com/rabbitmq/amqp091-go/pull/223

**Comment by lukebakken** [comment]
Thank you! 🏅
